version: '3.9'

services:
  web:
    build: .
    container_name: cerps_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis

  db:
    image: postgres:16
    container_name: cerps_db
    environment:
      POSTGRES_DB: Cerps
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: chloe2019.
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: cerps_redis
    ports:
      - "6379:6379"

volumes:
  pgdata:
